### Loading DATA INTO PANDAS

In [7]:
import pandas as pd
poke = pd.read_csv('pokemon_data.csv')
#print(poke.head(5))
#print(poke.tail(5))
#popke_xlsx = pd.read_excel('pokemon_data.xlsx') 
#print(poke_xlsx.head(5))
#for reading .txt file
#df = pd.read_csv('pokemon_data.txt', delimilter='\t')
#delimiter put only if the visiul is not appropriate
poke

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False

### Reading Data in Pandas

In [24]:
## read headeers
##print(poke.columns)
## read each column
##print(poke['Name'] [0:7])
##print(poke[['Name', 'Type 1', 'HP']])

## read each row
##print(poke.iloc[0:4])
#for index, row in poke.iterrows():
 #   print(index, row['Name'])
#poke.loc[poke['Type 1']=="Fire"] #its type 1 coloumn have all fire object specific I saw
    ## read a specific location(R,c)
##print(poke.iloc[2,1])

Sorting / Descri9bing Data

In [31]:
#describe Method
#poke.describe()
#sort method
#poke.sort_values('Name', ascending=False) #use = false its means oppsite side for the value(ascending)  
#poke.sort_values(['Type 1', 'HP'], ascending=[1,0]) # 1 = true and 0 = False. so here 0 stands for descending order for HP.

Making changes to the data

In [65]:
#poke['Total'] = poke['HP'] + poke['Attack'] + poke['Defense'] + poke['Sp. Atk'] + poke['Sp. Def'] + poke['Speed'] 
#poke.head(5)
poke['Total'] = poke.iloc[:, 4:10].sum(axis=1)# [:, 4,10] here : is for I use all the Row and 4to 10 index of row
cols = list(poke.columns.values)
cols = list(poke.columns)

#  whenever we mesh the rows for operation it include string so string function under in [] this bracket
#poke = poke[cols[0:4] + [cols[-1]] + cols[4:12]] #change the columns location 
#poke=poke[['Total', 'HP', 'Defense']]

poke.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

saving our data(export inti desired format)

In [68]:
# poke.to_csv('modified.csv') its for our modified data save in pc
#(modified.csv, index=false) so index ha deleted by it so that i remove unnessary data into the file
#for excel to_excel
#for text modified.text and set delimitor or sep='\t'
#new_poke make variable so changebal data I saved in this from
#new_poke.csv
#poke = poke.reset_index(drop=True, inplace = True) #for new indexing
#poke

Filtering Data

In [79]:
#p0oke.loc[(poke['Type 1'] == 'Grass') & ( poke['Type 2'] == 'Poison')] #for and
#poke.loc[(poke['Type 1'] == 'Grass') | ( poke['Type 2'] == 'Poison')] # for or
#poke.loc[(poke['Type 1'] == 'Grass') & ( poke['Type 2'] == 'Poison') &  ( poke['HP'] )]
# also we use < > oprators 
#poke.loc[poke['Name'].str.contains('Mega')] # its for specic filter a word in string and give output 
#poke.loc[~poke['Name'].str.contains('Mega')] # ~ its notation use for all the data remove have word to derive by me

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [82]:
import re #re=ragular expresson
#poke.loc[poke['Type 1'].str.contains('fire|grass', flags=re.I, regex=True)]
#flags=re.I after use this function upper case and lowercase all equal for function . fire|grass or FIRE|GRass we use.
#poke.loc[poke['Name'].str.contains('pi[a-z]*', flags=re.I, regex=True)]
#pi[a-z]* thats mean all string have pi words in their spelling are filter by function and use ^pi[a-z]* thats mean the word starting at pi.

conditional changes

In [90]:
#poke.loc[poke['Type 1'] == 'Fire', 'Type1'] = 'Flamer'#change|replace the fire word to flamer
#poke.loc[poke['Type 1'] == 'Fire', 'Legendary'] = True
#poke

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Type1
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,NaN
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,NaN
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,NaN
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,NaN
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,True,Flamer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,NaN
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,NaN
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,NaN
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,NaN
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Flamer

Aggregate Statistics

In [1]:

#poke.groupby(['Type 1']).mean() #find mean
#poke.groupby(['Type 1']).mean().sort_values('Defense', ascending=False) #sorting
#poke.groupby(['Type 1']).sum() #total sum
# for count function
#poke['count'] = 1
#poke.groupby(['Type 1']).count() ['count'] #how many for particular find column ['coumnsname']
#for multiple columns
#poke.groupby(['Type 1','Type 2'] ).count() ['count']
#poke

Working with large amoubnts of data